### ISSUE TITLE
Fortnite vpn failed 

### ISSUE THREAD

**Issue by Tygodi7s** [Crunnie/FNiOS-Archive#3]
![image](https://user-images.githubusercontent.com/43328312/219827193-d983e71a-f306-48a9-a6d0-a7d883b101f3.png)

after jumping off the bus, this error pops up on the iphone but I don't use vpn and the like(((( help

**Comment by Crunnie** [comment]
I suppose you are using v13.40.1. This is a issue I've been trying to find a fix/bypass for, sadly you can't sideload Season 13 on iOS, don't know what exactly is triggering it but it's something. If I find a fix, or even look for one (i'm not active in the FN comm anymore) I'll make sure to drop it somewhere :)

**Comment by Tygodi7s** [comment]
> I suppose you are using v13.40.1. This is a issue I've been trying to find a fix/bypass for, sadly you can't sideload Season 13 on iOS, don't know what exactly is triggering it but it's something. If I find a fix, or even look for one (i'm not active in the FN comm anymore) I'll make sure to drop it somewhere :)

do I need to download another version to solve the problem? and if so what

**Comment by Jishking98** [comment]
I’m having the same problem after I drop out the battle bus it kicks me out and gives me this erroer

**Comment by Jishking98** [comment]
Please help me

**Comment by Crunnie** [comment]
There's no current fix for this.
