### ISSUE TITLE
My Fortnite chapter 2 version 13.40.1 doesn’t download. #helpwanted

### ISSUE THREAD

**Issue by Jishking98** [Crunnie/FNiOS-Archive#4]
When I go in Fortnite and try to install it… it always keeps going up and then down so I reinstalled the app and yet again the same thing happend

**Comment by Crunnie** [comment]
Yup, that happened to me as well. I had to leave the app for a bit and it finally downloaded. Hope that helps! If you still have issues make sure to report em :)

**Comment by Jishking98** [comment]
I tried closed the app for a bit to download and when I come back it’s at 0 percent and Is going up and downs
Please help crunnie

**Comment by Jishking98** [comment]
If you don’t mind please make a dedicated video on this #

#helpwanted

**Comment by Jishking98** [comment]
Nvm it worked!

**Comment by Lucuferdev** [comment]
Where i get google drive link
